{% set name = "pysimdjson" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6bd39c666b6ad51bc120ed178b59ea761e500c570e487b6259b7f8d864c54ad

build:
  number: 0
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install '.[dev]' --no-binary all -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11
    - python
  run:
    - python

test:
  imports:
    - simdjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/TkTech/pysimdjson
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 and MIT

extra:
  recipe-maintainers:
    - CJ-Wright
