{% set name = "pysimdjson" %}
{% set version = "4.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d4f87259618d4464be0c4c6c367f72d8bcf91fcc9edb4c505f55722496a92eb

build:
  number: 0
  skip: true  # [py<36 or win]
  script: {{ PYTHON }} -m pip install '.[dev]' --no-binary all -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - pybind11
    - python
  run:
    - python

test:
  imports:
    - simdjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/TkTech/pysimdjson
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 and MIT

extra:
  recipe-maintainers:
    - CJ-Wright
