{% set name = "pysimdjson" %}
{% set version = "5.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83010f07f9ca38e4557b61860acfeb0a897b416f06f73182ffaffa94bdb7394d

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
  run:
    - python

test:
  imports:
    - simdjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/TkTech/pysimdjson
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 and MIT

extra:
  recipe-maintainers:
    - CJ-Wright
    - synapticarbors
