{% set name = "pysimdjson" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c57fa1da647b80d75a43301342a878708cac00f8d2fae79b6fcd9f036cb1f9ac

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
  run:
    - python

test:
  imports:
    - simdjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/TkTech/pysimdjson
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 and MIT

extra:
  recipe-maintainers:
    - CJ-Wright
    - synapticarbors
