schema_version: 1

context:
  name: pysimdjson
  version: "7.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: da6a23d8cbb9096d41fe6db2906ab6e6c0a2f42a652c9781eaf052049fe8783f
  patches:
    - pxd.patch

build:
  number: 0
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools >=74.1
  run:
    - python

tests:
  - python:
      imports:
        - simdjson
      pip_check: true

about:
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 AND MIT
  homepage: http://github.com/TkTech/pysimdjson

extra:
  recipe-maintainers:
    - CJ-Wright
    - synapticarbors
