schema_version: 1

context:
  name: pysimdjson
  version: 7.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: c57fa1da647b80d75a43301342a878708cac00f8d2fae79b6fcd9f036cb1f9ac

build:
  number: 0
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
        - python
        - cross-python_${{ target_platform }}
        - cython
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - setuptools >=74.1
  run:
    - python

tests:
  - python:
      imports:
        - simdjson
      pip_check: true

about:
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 and MIT
  homepage: http://github.com/TkTech/pysimdjson

extra:
  recipe-maintainers:
    - CJ-Wright
    - synapticarbors
